import { AnalysisResult } from './types';

// Template for the report
export function generateReportHtml(domain: string, analysis: AnalysisResult): string {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        body { font-family: 'Inter', sans-serif; margin: 0; padding: 40px; color: #1a1a1a; }
        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #551121; padding-bottom: 20px; margin-bottom: 40px; }
        .logo { font-size: 24px; font-weight: bold; color: #551121; }
        .title { font-size: 36px; font-weight: bold; margin-bottom: 10px; color: #551121; }
        .meta { color: #666; margin-bottom: 40px; }
        .score-card { background: #F6D6CA; padding: 30px; border-radius: 12px; text-align: center; margin-bottom: 40px; }
        .score-val { font-size: 72px; font-weight: 900; color: #551121; }
        .section { margin-bottom: 40px; }
        .section-title { font-size: 24px; font-weight: bold; color: #551121; border-left: 4px solid #E86A5A; padding-left: 15px; margin-bottom: 20px; }
        .check-item { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #eee; }
        .status-pass { color: #2B6B6E; font-weight: bold; }
        .status-fail { color: #E86A5A; font-weight: bold; }
        .footer { margin-top: 60px; border-top: 1px solid #eee; padding-top: 20px; text-align: center; font-size: 12px; color: #999; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo">BalloonSight</div>
        <div>${date}</div>
      </div>

      <div class="title">AI Visibility Report</div>
      <div class="meta">for ${domain}</div>

      <div class="score-card">
        <div class="score-val">${analysis.score}/100</div>
        <div>Overall AI Visibility Score</div>
      </div>

      <div class="section">
        <div class="section-title">Persona Analysis</div>
        <p><strong>Archetype:</strong> ${analysis.persona.archetype}</p>
        <p>${analysis.persona.description}</p>
      </div>

      <div class="section">
        <div class="section-title">Fix First (High Priority)</div>
        ${Object.values(analysis.categories).flatMap(c => c.checks).filter(c => c.status === 'fail').map(check => `
          <div class="check-item">
            <span>${check.label}</span>
            <span class="status-fail">Needs Fix</span>
          </div>
          <div style="font-size: 12px; color: #666; margin-bottom: 10px;">Fix: ${check.fix || 'See detailed guide.'}</div>
        `).join('')}
        ${Object.values(analysis.categories).flatMap(c => c.checks).filter(c => c.status === 'fail').length === 0 ? '<p>No critical failures found!</p>' : ''}
      </div>

      <div class="section">
        <div class="section-title">Detailed Breakdown</div>
        
        <h3>Accessibility (${analysis.categories.accessibility.score}%)</h3>
        ${analysis.categories.accessibility.checks.map(c => `
          <div class="check-item">
            <span>${c.label}</span>
            <span class="${c.status === 'pass' ? 'status-pass' : 'status-fail'}">${c.status.toUpperCase()}</span>
          </div>
        `).join('')}

        <h3 style="margin-top: 20px;">Structured Data (${analysis.categories.structuredData.score}%)</h3>
        ${analysis.categories.structuredData.checks.map(c => `
          <div class="check-item">
            <span>${c.label}</span>
            <span class="${c.status === 'pass' ? 'status-pass' : 'status-fail'}">${c.status.toUpperCase()}</span>
          </div>
        `).join('')}
      </div>

      <div class="footer">
        Generated by BalloonSight - balloonsight.com
      </div>
    </body>
    </html>
  `;
}

export async function generatePdf(html: string): Promise<Buffer> {
  // Lazy load puppeteer to avoid build crashes if not installed
  let puppeteer;
  try {
    puppeteer = await import('puppeteer');
  } catch (e) {
    console.warn('Puppeteer not found, skipping PDF generation');
    return Buffer.from('PDF generation failed: Puppeteer not installed');
  }

  const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
    headless: true
  });
  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: 'networkidle0' });
  const pdf = await page.pdf({ format: 'A4', printBackground: true });
  await browser.close();
  return Buffer.from(pdf);
}

